[phases.setup]
nixPkgs = ["python311Full", "nodejs_18"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node dist/server.js"
